apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openlearn-mariadb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openlearn-mariadb
    spec:
      volumes:
      - name: data
        emptyDir: {}
      containers:
      - name: mariadb
        image: mariadb:10.1.17
        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: 'yes'
        - name: MYSQL_DATABASE
          value: openlearn
#        command:
#        - mysqld
#        - --lower_case_table_names=1
#        - --skip-ssl
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql/
---
apiVersion: v1
kind: Service
metadata:
  name: openlearn-mariadb
spec:
  selector:
    app: openlearn-mariadb
  ports:
  - port: 3306
